apiVersion: v2
name: vector
version: 0.49.0
description: Helm chart to install Vector
type: application
dependencies:
  - name: vector
    repository: "https://helm.vector.dev"
    version: "0.49.0"
    # https://artifacthub.io/packages/helm/vector/vector
